### ISSUE TITLE
[Spotify Genres] [Feature Request] Display genre on artist pages

### ISSUE THREAD

**Issue by WildGenius** [Tetrax-10/Spicetify-Extensions#10]
As requested for the similar extension (https://github.com/Shinyhero36/Spicetify-Genre/issues/13), would be nice to be able to see the artist's genres, e.g., under their name.

**Comment by Tetrax-10** [comment]
Sure, I will do it when i have time

**Comment by Tetrax-10** [comment]
Done 🎉. I noticed that your feature request on [Shinyhero36/Spicetify-Genre](https://github.com/Shinyhero36/Spicetify-Genre/issues/13) Page is like 4 months old, Damn. It just took me solid 15 mins.

Hope you like it. If you like it feel free to like this repo 🤗.

Feel free to open a issue if you face any issues.

![artist-page](https://user-images.githubusercontent.com/75513645/216792489-8a8f1e83-12ea-4aea-bde6-ad478d96d676.png)

**Comment by WildGenius** [comment]
Great stuff! To be clear, the other request is not mine, I just linked it since it seemed to have some relevant info.

**Comment by D3SOX** [comment]
Thanks for implementing this!

**Comment by WildGenius** [comment]
Would it be possible to also allow to open the popup menu with the Last.FM tags by right-clicking an artist genre? Should I open a separate request for that?

**Comment by Tetrax-10** [comment]
> Would it be possible to also allow to open the popup menu with the Last.FM tags by right-clicking an artist genre?

I will do that in future

> Should I open a separate request for that?

Yes please.
