### ISSUE TITLE
[Spotify Genres] [Idea] Display by artist in genre modal

### ISSUE THREAD

**Issue by D3SOX** [Tetrax-10/Spicetify-Extensions#11]
In this example, it only shows the genres of the first artist in the

<details>
<summary>
player bar
</summary>

![image](https://user-images.githubusercontent.com/24937357/216817010-b2f4b495-bfad-447c-86f5-5e237a6c1327.png)

</details>

and only the ones from the second artist in

<details>
<summary>
the modal
</summary>

![image](https://user-images.githubusercontent.com/24937357/216817016-1432bab0-bc4b-4c78-85c2-f20f0f423df2.png)
</details>

I think it would be a nice addition to show the genres grouped by artists in the popup.

### Genres from artist [Jacidorex]()
[`acidcore`](https://open.spotify.com/playlist/23TcHEHll7Ds78hkaiohPx) [`belgian techno`](https://open.spotify.com/playlist/3PBhul1KmVf1JVSErEgypU)
### Genres from artist [Marie Vaunt](https://open.spotify.com/artist/50KydUSYhBFGorhAgUcrL5)
[`techno rave`](https://open.spotify.com/playlist/0FQBLVXObEachBjozNnbpM) [`french techno`](https://open.spotify.com/playlist/0eHVWJjMBIcxsdcgc6gtXt)

**Comment by Tetrax-10** [comment]
Check now and tell me. If you still face the issue then let me know
