### ISSUE TITLE
[Spotify Genres] [Bug] Genres shown are not consistent

### ISSUE THREAD

**Issue by D3SOX** [Tetrax-10/Spicetify-Extensions#12]
I noticed that there is some bug where it shows different or no genres at all. I'm not exactly sure what I did, but it previously showed

<details>
<summary>
these genres
</summary>

![image](https://user-images.githubusercontent.com/24937357/216817021-c372a15b-d559-4eb5-939c-271f897318c7.png)
</details>

<details>
<summary>
then these
</summary>

![image](https://user-images.githubusercontent.com/24937357/216817493-53a84731-55f1-4bf2-a35e-b517db2052db.png)
</details>

<details>
<summary>
and now no genres at all (artist page and player bar)
</summary>

![image](https://user-images.githubusercontent.com/24937357/216818113-5657c4c3-4ae8-4e25-859f-9e39bc8d56f7.png)
![image](https://user-images.githubusercontent.com/24937357/216818118-ab6c8f0e-7b38-4b2e-9bd2-2178666f4ee5.png)
</details>

I only clicked around on some artists and playlists. Restarting Spotify doesn't change anything. Other artists still work at the moment.
Let me know if you need any debug logs and how to grab them.

Spotify's API seems to return no genres at all for this artist btw
![image](https://user-images.githubusercontent.com/24937357/216818417-9049b36e-7c75-446f-93e4-d08be1e05f31.png)

---

Also fetching from last.fm doesn't seem to work, at least not for this artist, as it shows

<details>
<summary>
some tags on the artist page

(<https://www.last.fm/music/Marie+Vaunt>)

</summary>

![image](https://user-images.githubusercontent.com/24937357/216817832-4a653ee7-4b23-4359-b00b-da832ed3d5f6.png)
</details>

<details>
<summary>
which are not shown in the modal
</summary>

![image](https://user-images.githubusercontent.com/24937357/216817016-1432bab0-bc4b-4c78-85c2-f20f0f423df2.png)
</details>

**Comment by Tetrax-10** [comment]
Fixed artist inconsistent bug 🎉.

> Spotify's API seems to return no genres at all for this artist btw ![image](https://user-images.githubusercontent.com/24937357/216818417-9049b36e-7c75-446f-93e4-d08be1e05f31.png)

Yeah That artist doesnt have genre data. What this extension does to get her genre is by getting related artist's genres.

![image](https://user-images.githubusercontent.com/75513645/216824136-887ed555-df58-4ee8-a2c9-1778754a1884.png)

These artist's top genres will be taken as `Marie Vaunt's` genre (Marie Vaunt's related artists. Totally 20 related artists for a artist )

![image](https://user-images.githubusercontent.com/75513645/216824181-99d3c722-96a3-44a6-8e22-49bbb56e1147.png)

> Also fetching from last.fm doesn't seem to work, at least not for this artist, as it shows
> 
> some tags on the artist page
> (https://www.last.fm/music/Marie+Vaunt)
> 
> which are not shown in the modal

Last Fm tags are not artist specific, they are song specific.

```https://www.last.fm/music/Marie+Vaunt/_/Acid+in+Your+Mind+-+Original+Mix```

I cant do much about this one as the API itself returns empty tags

![image](https://user-images.githubusercontent.com/75513645/216824989-e97c0bf6-bfd6-4402-bb61-680116a2d207.png)

**Comment by D3SOX** [comment]
> What this extension does to get her genre is by getting related artist's genres.

Ah I wasn't aware of that, good to know

> Last Fm tags are not artist specific, they are song specific.

Didn't know that too


---

Now it seems to show the related genres of the artist page of the currently playing track, even if it's not from that artist

![image](https://user-images.githubusercontent.com/24937357/216844914-62c1a466-42e8-4684-93dc-cdb84309939b.png)
![image](https://user-images.githubusercontent.com/24937357/216844917-1798459f-b068-41d7-bdb6-0505b193b305.png)

**Comment by Tetrax-10** [comment]
I think your marketplace didnt update the extension.

Its working fine for me. Try checking now

![image](https://user-images.githubusercontent.com/75513645/216955266-421de0d2-b7ad-41f5-81d9-f1d052f968b9.png)

![image](https://user-images.githubusercontent.com/75513645/216955361-afda2f41-019d-4cf4-ab1a-c6c6da4db03b.png)

> ![image](https://user-images.githubusercontent.com/24937357/216844917-1798459f-b068-41d7-bdb6-0505b193b305.png)

Marie Vaunt's genre are these in my pic. You didnt get the update I think. A update takes 12 to 24 hrs for marketplace. may be try installing manually

![image](https://user-images.githubusercontent.com/75513645/216955309-5653cff4-ac40-40e4-af34-2e4a10215fa1.png)

**Comment by Tetrax-10** [comment]
If your issue is solved please close this issue

**Comment by D3SOX** [comment]
I'm not using the marketplace. I just cloned the repo and symlinked the `.js`. I didn't have time to check on this again. I will update you then

**Comment by Tetrax-10** [comment]
If your issue is fixed feel free to close this issue

**Comment by D3SOX** [comment]
No, I don't know how to explain it to you / report it but it's still buggy
![image](https://user-images.githubusercontent.com/24937357/218696870-702294b3-9245-4c6a-9ce9-36a221ec3071.png)

**Comment by Tetrax-10** [comment]
Post the previous track and current track link, so i can verify.
