### ISSUE TITLE
[Play Enhanced Songs] [Bug] It plays the same enhanced songs even after adding or removing an enhanced song from playlist

### ISSUE THREAD

**Issue by mkwiimaster7** [Tetrax-10/Spicetify-Extensions#14]

**Comment by Tetrax-10** [comment]
I cant replicate that bug.

### **What I did:**

clicked play enhanced songs then 11 songs played.
I added the first song to my playlist
then again clicked play enhanced songs then 10 songs played
those 10 songs are not in my playlist.

It would be easy if you explain more about the bug with screenshot or mp4

**Comment by mkwiimaster7** [comment]
![image](https://user-images.githubusercontent.com/9386565/218538644-f479a852-c3ae-4e02-a688-6929906e6d13.png)

This was right after i pressed play enhanced songs. Its supposed to start playing money trees, but instead it plays a song ive already added to my playlist
