### ISSUE TITLE
[Spotify Genres] [Feature Request] Sort/filter existing playlist by genre

### ISSUE THREAD

**Issue by joshuayuen99** [Tetrax-10/Spicetify-Extensions#15]
A way to take an existing playlist or entire music library and filter it by genre. This would also allow easily creating new playlists for a certain genre/set of genres by filtering and then adding all to a playlist.

**Comment by Tetrax-10** [comment]
That should be a whole new different extension, As this extension just gets the genre when a song is played. Great suggesion for a new extension but I am afraid that I wont have enough time to Implement that.
