### ISSUE TITLE
How to add genres to the tracklist？

### ISSUE THREAD

**Issue by youthyan** [Tetrax-10/Spicetify-Extensions#16]
I found a js extension that displays bpm in the track list, 
how can I modify the api of this js to replace bpm info with genre. 
Thank you very much if you can.
<img width="990" alt="截屏2023-05-01 下午4 59 10" src="https://user-images.githubusercontent.com/105373147/235432114-4b11c774-9ec2-4cfc-9871-bf3a9598ebf4.png">

**Comment by youthyan** [comment]
// This is the js extension to display bpm, I want to replace bpm with genre
// Here is a screenshot of the extension, it works fine
// screenshot 
<img width="754" alt="截屏2023-05-01 下午5 06 26" src="https://user-images.githubusercontent.com/105373147/235432863-ac454411-f56a-4792-a4a6-f21815334ba5.png">

 (async function djInfoList() {
    while (!Spicetify.showNotification) {
        await new Promise((resolve) => setTimeout(resolve, 500))
    }
    const { CosmosAsync, ContextMenu, URI } = Spicetify;
    if (!(CosmosAsync && URI)) {
        setTimeout(djInfoList, 300)
        return
    }

    const fiveColumnGridCss = "[index] 16px [first] 3fr [var1] 2fr [var2] 3fr [last] minmax(120px,1fr)"
    const sixColumnGridCss = "[index] 16px [first] 5fr [var1] 3fr [var2] 2fr [var3] 3fr [last] minmax(120px,1fr)"
    const sevenColumnGridCss = "[index] 16px [first] 5fr [var1] 3fr [var2] 2fr [var3] minmax(120px,1fr) [var3] 3fr [last] minmax(120px,1fr)"

    const waitForElement = (selector) => {
        return new Promise((resolve) => {
            if (document.querySelector(selector)) {
                return resolve(document.querySelector(selector))
            }
            const observer = new MutationObserver(() => {
                if (document.querySelector(selector)) {
                    observer.disconnect()
                    resolve(document.querySelector(selector))
                }
            })
            observer.observe(document.body, {
                childList: true,
                subtree: true,
            })
        })
    }

    function getTracklistTrackUri(tracklistElement) {
        let values = Object.values(tracklistElement)
        if (!values) return null

        return (
            values[0]?.pendingProps?.children[0]?.props?.children?.props?.uri ||
            values[0]?.pendingProps?.children[0]?.props?.children?.props?.children?.props?.uri ||
            values[0]?.pendingProps?.children[0]?.props?.children[0]?.props?.uri
        )
    }

    function getPageType() {
        const pathname = Spicetify.Platform.History.location.pathname
        let matches = null
        if (pathname === "/collection/tracks") {
            return ["LIKED_SONGS", null]
        }
        if ((matches = pathname.match(/playlist\/(.*)/))) {
            return ["PLAYLIST", matches[1]]
        }
        if ((matches = pathname.match(/album\/(.*)/))) {
            return ["ALBUM", matches[1]]
        }
        if ((matches = pathname.match(/artist\/([^/]*)$/))) {
            return ["ARTIST", matches[1]]
        }
        if ((matches = pathname.match(/artist\/([^/]*)\/saved/))) {
            return ["ARTIST_LIKED", matches[1]]
        }
        return ["OTHER", null]
    }

    let oldTracklist = null
    let tracklist = null

    let updateTracklist = null

    updateTracklist = async () => {
        const tracklist_ = document.querySelector(".main-trackList-indexable")
        if (!tracklist_) return
        const tracks = tracklist_.getElementsByClassName("main-trackList-trackListRow")

        const tracklistHeader = document.querySelector(".main-trackList-trackListHeaderRow")
        // No tracklist header on Artist page
        if (tracklistHeader) {
            let lastColumn = tracklistHeader.querySelector(".main-trackList-rowSectionEnd")
            let colIndexInt = parseInt(lastColumn.getAttribute("aria-colindex"))

            switch (colIndexInt) {
                case 4:
                    tracklistHeader.style["grid-template-columns"] = fiveColumnGridCss
                    break
                case 5:
                    tracklistHeader.style["grid-template-columns"] = sixColumnGridCss
                    break
                case 6:
                    tracklistHeader.style["grid-template-columns"] = sevenColumnGridCss
                    break
                default:
                    break
            }
        }
        for (const track of tracks) {
            const heart = track.getElementsByClassName("main-addButton-button")[0]
            const hasdjinfo = track.getElementsByClassName("djinfo").length > 0
            const trackUri = getTracklistTrackUri(track)
            const isTrack = trackUri.includes("track")

            let ratingColumn = track.querySelector(".djInfoList")
            if (!ratingColumn) {
                // Add column for djInfos
                let lastColumn = track.querySelector(".main-trackList-rowSectionEnd")
                let colIndexInt = parseInt(lastColumn.getAttribute("aria-colindex"))
                lastColumn.setAttribute("aria-colindex", (colIndexInt + 1).toString())
                ratingColumn = document.createElement("div")
                ratingColumn.setAttribute("aria-colindex", colIndexInt.toString())
                // ratingColumn.role = "gridcell"
                ratingColumn.style.display = "flex"
                ratingColumn.classList.add("main-trackList-rowSectionVariable")
                ratingColumn.classList.add("djInfoList")
                track.insertBefore(ratingColumn, lastColumn)

                switch (colIndexInt) {
                    case 4:
                        track.style["grid-template-columns"] = fiveColumnGridCss
                        break
                    case 5:
                        track.style["grid-template-columns"] = sixColumnGridCss
                        break
                    case 6:
                        track.style["grid-template-columns"] = sevenColumnGridCss
                        break
                    default:
                        break
                }


async (artistURI) => {
    const res = await CosmosAsync.get(`https://api.spotify.com/v1/artists/${artistURI}`);
    setBg(res.name);
  };
                if (!heart || !trackUri || hasdjinfo || !isTrack) continue
                var text = document.createElement('p');
                var uri = trackUri;
                var uriFinal = uri.split(":")[2]
                var res = await CosmosAsync.get('https://api.spotify.com/v1/audio-features/' + uriFinal);
                text.innerHTML = `${Math.round(res.tempo)} BPM`;
                text.classList.add("djinfo-${k}")
                text.classList.add("djinfo")
                text.style.fontSize = "12px"
                ratingColumn.appendChild(text)
            }
            if (!heart || !trackUri || hasdjinfo || !isTrack) continue
        }
    }
    const tracklistObserver = new MutationObserver(() => {
        updateTracklist()
    })

    const observerCallback = async () => {
        oldTracklist = tracklist
        tracklist = document.querySelector(".main-trackList-indexable")
        if (tracklist && !tracklist.isEqualNode(oldTracklist)) {
            if (oldTracklist) {
                tracklistObserver.disconnect()
            }
            ;[pageType, id] = getPageType()
            updateTracklist()
            tracklistObserver.observe(tracklist, {
                childList: true,
                subtree: true,
            })
        } 
    }

    const observer = new MutationObserver(observerCallback)
    await observerCallback()
    observer.observe(document.body, {
        childList: true,
        subtree: true,
    })


})();

**Comment by youthyan** [comment]
Seeing that you have developed a lot of extensions,
 I think you are very powerful,
 can you help me, thank you very much,

**Comment by Tetrax-10** [comment]
> Seeing that you have developed a lot of extensions, I think you are very powerful

Thx ✌️

Didnt you read [this](https://github.com/Tetrax-10/Spicetify-Extensions#spicetify-extensions)? Ping me in [discord](https://discord.gg/VnevqPp2Rr) for help/discussions

![image](https://user-images.githubusercontent.com/75513645/235441400-cc3f28e4-002e-4d65-ae98-e30977e0cf08.png)
