### ISSUE TITLE
genres no longer display on artist pages

### ISSUE THREAD

**Issue by G0LD3NR0D** [Tetrax-10/Spicetify-Extensions#18]
Description of problem: artist genres no longer display on their pages as intended, while genres still display in the player bar.

Reproduction steps: Install the spotify-genres extension and reload spotify, then go to any artist's page. (I have reproduced this three times across three different computers.)

Attempts to fix: restarted app, uninstalled and reinstalled the extension, uninstalled all other extensions, disabled themes, did a full reinstall of the app.

I'm unsure what's going on here, this behavior is consistent despite my attempts to fix it. I won't stop using this extension but being able to see artist's genres even if it's pulling from related artists is really quite useful for me.

**Comment by Tetrax-10** [comment]
Send me your config and need screenshot of your artist page

**Comment by G0LD3NR0D** [comment]
Still kinda new to using spicetify, so when you ask for my config what exactly are you referring to, and where should I look for that?

Here's an example artist page, showing that artist genres don't display.
![image](https://github.com/Tetrax-10/Spicetify-Extensions/assets/134349471/9957d87c-5a2d-4a72-85dc-fb1255acbc77)

**Comment by G0LD3NR0D** [comment]
Here's the config file then. I'm running Spicetify 2.18.1 which is up to date, and since I reinstalled spotify more than once it should be the newest version as well. Since github doesn't support uploading ini files for issues I zipped it up.
[config-xpui.zip](https://github.com/Tetrax-10/Spicetify-Extensions/files/11560427/config-xpui.zip)

**Comment by Tetrax-10** [comment]
Fixed it. Sry for the confusion I was using a more later version of Spicetify where they add support for [widgets](https://github.com/spicetify/spicetify-cli/pull/2347) which is yet to release. So that caused the issue for users.

![image](https://github.com/Tetrax-10/Spicetify-Extensions/assets/75513645/243ff90a-f0de-4db4-9455-69408889936d)


Thx for reporting 💖.
