### ISSUE TITLE
[Spotify Genres] [Bug] Trailing comma on some artists

### ISSUE THREAD

**Issue by Aimarekin** [Tetrax-10/Spicetify-Extensions#19]
Genres are shown with a trailing comma on this artist which has only one genre:
![image](https://github.com/Tetrax-10/Spicetify-Extensions/assets/38393797/5878d0e0-794b-44fd-b9a7-cad2388b81ae)
[`spotify:artist:3Hb64DQZIhDCgyHKrzBXOL`](https://open.spotify.com/artist/3Hb64DQZIhDCgyHKrzBXOL)

This other artist who also has only one genre does not have a trailing comma:
![image](https://github.com/Tetrax-10/Spicetify-Extensions/assets/38393797/06877c0f-a262-47d8-a384-c9dabbb86646)
[`spotify:artist:5WoWlP0ihSFIxnppxjwSgE`](https://open.spotify.com/artist/5WoWlP0ihSFIxnppxjwSgE)

I don't believe I have observed this behavior with artists with one more than one genre.

**Comment by Tetrax-10** [comment]
Try checking the latest build should be fixed.

![image](https://github.com/Tetrax-10/Spicetify-Extensions/assets/75513645/7dfc2577-92b5-4c9c-869b-f15fd9c043b5)
