### ISSUE TITLE
0/1 to API Logic

### ISSUE THREAD

**Issue by CharlieS1103** [Tetrax-10/Spicetify-Extensions#2]
Right now, it's checking if the song is liked, if it isn't it skips. This can create an infinite loop of sorts rather easily, I recommend changing it so it will fetch all of the users liked songs via Spotify's API, shuffle them (should be as simple as shuffling an array), and then simply add them to a queue.

**Comment by Tetrax-10** [comment]
@CharlieS1103 At first, I thought this API logic but found some limitations,

1) I created it as I discover new songs from others' playlists. I usually change the sort type in between and play it in a different order. With Spotify API we cant get it sorted ( of course we can sort it by getting `date added`, `duration`, `title`, and `artist` from API, but what about `Custom order`, `Shuffle+`, `Custom queue` created by the user )

2) What if the User has liked 1000s and 1000s of songs and listens to a playlist that has 1000s of songs ( me, an average listener having 6000+ liked songs sometimes listens to a huge community playlist that has nearly 8000 songs just to hear 3 to 4 songs ), then API, sort and queue process will take more than 3s for an average PC ( Reference - `listPlaylistsWithSong.js` ).

3) What if the user changes the `mode` in between, we need to repeat the whole process again 3s delay.

4) What if the user like/removes a song and plays it in a `different order` the queue remains `un updated`.

These are the limitations I had with `API logic`, So I implemented a very easy logic that won't have these limitations.

What do you mean by "infinite loop of sorts"? am not sorting any songs.

The only problem I face is that if this script encounters more than 100 liked songs on `skip liked` mode the inbuilt `playNext` function crashes. I will probably fix it in the next version by adding a `setTimeout` function.

**Comment by Tetrax-10** [comment]
If I face any issues or bugs with 0/1 logic sure I will try to implement API logic. I don't think any infinity loop will happen because whenever a listener is created it is automatically removed with other events. If you face any issues please create an issue. Thanks for giving enhancement ideas.

**Comment by CharlieS1103** [comment]
@Tetrax-10 Just created an infinite loop simply by triggering the play liked song only feature and playing a playlist which has no songs I've liked in it.

**Comment by Tetrax-10** [comment]
Spotify plays similar songs after a playlist ends, in that similar songs only liked songs will play if you enable `play liked only` mode. we can't predict and add these songs with API Logic.

![working as expected](https://user-images.githubusercontent.com/75513645/175456988-07f04e1c-0959-4555-8113-303e3edfefee.gif)
