### ISSUE TITLE
[Spotify Genres] [Feature Request] Move toggle to profile menu

### ISSUE THREAD

**Issue by D3SOX** [Tetrax-10/Spicetify-Extensions#20]
I don't need the new hide genres button and I don't think one would need to toggle this very often, so I'd say it should be inside the profile menu instead, like some other plugins implement it
![image](https://github.com/Tetrax-10/Spicetify-Extensions/assets/24937357/a0450c42-e74c-4177-ab3d-b3779586c305)

**Comment by Tetrax-10** [comment]
I think having the toggle in the player is the best option as its quick to toggle. where as in context menu users need to open the profile context menu then toggle it.
