### ISSUE TITLE
"Sort by Play Count" extension is not adding songs to queue

### ISSUE THREAD

**Issue by felipeconter** [Tetrax-10/Spicetify-Extensions#4]
First time using the extension, installed it from the spicetify marketplace.

But clicking on "sort by" anything, it shows notifications of counting the tracks/albums, but fails with this message:
> ForbiddenError: PUT request to sp://player/v2/main/queue failed with status code 403

Since it's my fist time using it, i may be doing something wrong.

**Comment by notPlancha** [comment]
did you register last.fm username?

**Comment by felipeconter** [comment]
no, but i was not intending to use lastfm integration.
i'll try that.

Felipe Pierre Conter
***@***.***


Em qua., 31 de ago. de 2022 às 11:48, notPlancha ***@***.***>
escreveu:

**Comment by felipeconter** [comment]
- i put my lastfm username in the config menu;
- i did "sort by my scrobbles" - this worked;
- after that all sorting methods started working.

thanks!

**Comment by Tetrax-10** [comment]
All Fine now? any problems feel free to create a issue.

Anyway check out todays [2.1](https://github.com/Tetrax-10/Spicetify-Extensions/commit/4d0021a69db5a3e2ea4d5bb93a005d7ca93cb97f) release. In marketplace you have to wait for 24hrs to get next version
