### ISSUE TITLE
Sort By extension not sorting or adding to Sorted Playlist folder

### ISSUE THREAD

**Issue by obzen900** [Tetrax-10/Spicetify-Extensions#5]
ForbiddenError: PUT request to sp://player/v2/main/queue failed with status code 403

At first I installed via Marketplace (it didn't work), so I removed it via Marketplace. I then installed it manually and applied via Powershell (it didn't work). Looked up closed issues and tried what another user did which was logging into Last.fm again, selecting to sort by Last.fm Play Count then by Spotify Play Count (it didn't work). how do I remove from Marketplace completely, and if that's not the case what am I doing wrong?

**Comment by Tetrax-10** [comment]
Everything is working fine for me. Can you send some ss and console errors. I can create playlist in all modes. is it happening is a particular mode? then what mode it is?

I wont recommended installing anything from marketplace just do it manually.

**Comment by obzen900** [comment]
After removing the Marketplace installs completely by resetting Spicetify completely, and then doing a fresh manual install of Spicetify and the Sort By extension it works like a charm. Unfortunately, I had 4 different installs of Spicetify me tinkering around.

Issue was on my end. It is fixed, and your extensions are wonderful.

**Comment by Tetrax-10** [comment]
> After removing the Marketplace installs completely by resetting Spicetify completely, and then doing a fresh manual install of Spicetify and the Sort By extension it works like a charm. Unfortunately, I had 4 different installs of Spicetify me tinkering around.
> 
> Issue was on my end. It is fixed, and your extensions are wonderful.

Thanks for you appreciation ❤️. Leaving a Like will be more appreciable 🥰
