### ISSUE TITLE
ForbiddenError

### ISSUE THREAD

**Issue by shadow90810** [Tetrax-10/Spicetify-Extensions#6]
Hi, im also getting error

ForbiddenError: PUT request to sp://player/v2/main/queue failed with status code 403

Ive tried uninstalled and installed multiple times. Manual and marketplace.

When installed, should there be other files in the extension folder? Because all i have is the .js file that i put in there

**Comment by Tetrax-10** [comment]
in what mode you are getting this error? like playlist, album, artist? also playcount, popularity, release date?

**Comment by shadow90810** [comment]
In playlist mode. Im trying to sort my custom playlists.

Also, same error when trying to sort by any other method like release date

Thank u for the quick reply

**Comment by shadow90810** [comment]
Ok. I got it to work. you have to play a song from the playlist before you can use sort. however it doesn't actually sort the playlist.

it adds all the song to a queue in the order the you wanted it sorted. go to the queue and you will see the playlist in the sorted format.

**Comment by Tetrax-10** [comment]
> Ok. I got it to work. you have to play a song from the playlist before you can use sort.

No need to play a song before sorting. 

> it adds all the song to a queue in the order the you wanted it sorted.

Yes exactly
