### ISSUE TITLE
Sorting Removes Songs

### ISSUE THREAD

**Issue by JoshuaFern** [Tetrax-10/Spicetify-Extensions#7]
Reproduce:
Take a fairly large playlist and sort by popularity, for example. 
Hit the + button to create a new playlist with that custom order. Note the previous total songs in the playlist compared to the new count.

I think what's happening here is that sometimes playlists contain songs that are greyed out, perhaps missing from Spotify at the moment and the extension does not attempt to preserve them.

**Comment by Tetrax-10** [comment]
Sort by Play Count cant sort if the song does not have necessary sorting data.

mostly a new song that has been released within 24hrs wont have that data. (or) the song is heared by very few people (0 to 1000) so spotify doesnt provide playcount/popularity details

it doesnt delete anything from the original playlist. it just ignores song that dont have necessary sorting  data
