### ISSUE TITLE
ForbiddenError

### ISSUE THREAD

**Issue by CherryLax** [Tetrax-10/Spicetify-Extensions#9]
I've gotten an error after adding my Last.FM username, restarting, and choosing any of the bottom three sort types:
![image](https://user-images.githubusercontent.com/4121967/211173902-deed8bbb-2c90-4f59-b69b-034b87749445.png)

![image](https://user-images.githubusercontent.com/4121967/211173876-39dc53f1-e743-4981-acf9-545bc9b28326.png)

![image](https://user-images.githubusercontent.com/4121967/211173926-b59a1bd6-74b1-4292-b903-51573f212a9d.png)

Let me know if you need any further info

**Comment by Tetrax-10** [comment]
works fine for me. you can try installing latest spotify and spicetify, even re-install sort by play count extension
